export const brazilStates = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO"
] as const;

export const brazilTimezones = [
  "America/Araguaina",
  "America/Bahia",
  "America/Belem",
  "America/Boa_Vista",
  "America/Campo_Grande",
  "America/Cuiaba",
  "America/Eirunepe",
  "America/Fortaleza",
  "America/Maceio",
  "America/Manaus",
  "America/Noronha",
  "America/Porto_Velho",
  "America/Recife",
  "America/Rio_Branco",
  "America/Santarem",
  "America/Sao_Paulo"
] as const;

export const timezoneByState: Record<(typeof brazilStates)[number], (typeof brazilTimezones)[number]> = {
  AC: "America/Rio_Branco",
  AL: "America/Maceio",
  AP: "America/Belem",
  AM: "America/Manaus",
  BA: "America/Bahia",
  CE: "America/Fortaleza",
  DF: "America/Sao_Paulo",
  ES: "America/Sao_Paulo",
  GO: "America/Sao_Paulo",
  MA: "America/Fortaleza",
  MT: "America/Cuiaba",
  MS: "America/Campo_Grande",
  MG: "America/Sao_Paulo",
  PA: "America/Belem",
  PB: "America/Recife",
  PR: "America/Sao_Paulo",
  PE: "America/Recife",
  PI: "America/Fortaleza",
  RJ: "America/Sao_Paulo",
  RN: "America/Fortaleza",
  RS: "America/Sao_Paulo",
  RO: "America/Porto_Velho",
  RR: "America/Boa_Vista",
  SC: "America/Sao_Paulo",
  SP: "America/Sao_Paulo",
  SE: "America/Maceio",
  TO: "America/Araguaina"
};
