export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      condominiums: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          slug: string;
          timezone: string;
          settings: Json;
          operational_rules: Json;
          visitor_parking_capacity: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          slug: string;
          timezone?: string;
          settings?: Json;
          operational_rules?: Json;
          visitor_parking_capacity?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          slug?: string;
          timezone?: string;
          settings?: Json;
          operational_rules?: Json;
          visitor_parking_capacity?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          tenant_id: string;
          full_name: string;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          tenant_id: string;
          full_name: string;
          role: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          full_name?: string;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      condominium_memberships: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          profile_id: string;
          role: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          profile_id: string;
          role: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          profile_id?: string;
          role?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      units: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          block: string | null;
          number: string;
          floor: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          block?: string | null;
          number: string;
          floor?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          block?: string | null;
          number?: string;
          floor?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      access_points: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          name: string;
          kind: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          name: string;
          kind: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          name?: string;
          kind?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      residents: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          full_name: string;
          document: string | null;
          phone: string | null;
          email: string | null;
          profile_id: string | null;
          status: string;
          block_reason: string | null;
          blocked_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          full_name: string;
          document?: string | null;
          phone?: string | null;
          email?: string | null;
          profile_id?: string | null;
          status?: string;
          block_reason?: string | null;
          blocked_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          full_name?: string;
          document?: string | null;
          phone?: string | null;
          email?: string | null;
          profile_id?: string | null;
          status?: string;
          block_reason?: string | null;
          blocked_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      resident_units: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id: string;
          relationship: string;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id: string;
          relationship?: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          resident_id?: string;
          unit_id?: string;
          relationship?: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      resident_vehicles: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          plate: string;
          label: string | null;
          status: string;
          block_reason: string | null;
          blocked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          plate: string;
          label?: string | null;
          status?: string;
          block_reason?: string | null;
          blocked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          resident_id?: string;
          plate?: string;
          label?: string | null;
          status?: string;
          block_reason?: string | null;
          blocked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      visitors: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          full_name: string;
          document: string | null;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          full_name: string;
          document?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          full_name?: string;
          document?: string | null;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      visitor_vehicles: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          visitor_id: string;
          plate: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          visitor_id: string;
          plate: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          visitor_id?: string;
          plate?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      visitor_unit_visits: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          visitor_id: string;
          unit_id: string;
          occurred_at: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          visitor_id: string;
          unit_id: string;
          occurred_at?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          visitor_id?: string;
          unit_id?: string;
          occurred_at?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      access_invites: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          unit_id: string | null;
          resident_id: string | null;
          visitor_id: string | null;
          visitor_name: string;
          visitor_phone: string | null;
          plate: string | null;
          starts_at: string;
          expires_at: string;
          max_uses: number;
          use_count: number;
          status: string;
          invite_type: string;
          recurrence_rule: string | null;
          qr_token_hash: string | null;
          qr_token_expires_at: string | null;
          cancelled_by: string | null;
          cancelled_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          unit_id?: string | null;
          resident_id?: string | null;
          visitor_id?: string | null;
          visitor_name: string;
          visitor_phone?: string | null;
          plate?: string | null;
          starts_at?: string;
          expires_at: string;
          max_uses?: number;
          use_count?: number;
          status?: string;
          invite_type?: string;
          recurrence_rule?: string | null;
          qr_token_hash?: string | null;
          qr_token_expires_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          unit_id?: string | null;
          resident_id?: string | null;
          visitor_id?: string | null;
          visitor_name?: string;
          visitor_phone?: string | null;
          plate?: string | null;
          starts_at?: string;
          expires_at?: string;
          max_uses?: number;
          use_count?: number;
          status?: string;
          invite_type?: string;
          recurrence_rule?: string | null;
          qr_token_hash?: string | null;
          qr_token_expires_at?: string | null;
          cancelled_by?: string | null;
          cancelled_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      access_invite_validations: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          invite_id: string | null;
          validated_by: string | null;
          result: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          invite_id?: string | null;
          validated_by?: string | null;
          result: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          invite_id?: string | null;
          validated_by?: string | null;
          result?: string;
          reason?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      access_events: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          access_point_id: string | null;
          invite_id: string | null;
          resident_id: string | null;
          visitor_id: string | null;
          plate: string | null;
          direction: string;
          decision: string;
          reason: string | null;
          decided_by: string | null;
          decided_at: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          access_point_id?: string | null;
          invite_id?: string | null;
          resident_id?: string | null;
          visitor_id?: string | null;
          plate?: string | null;
          direction: string;
          decision: string;
          reason?: string | null;
          decided_by?: string | null;
          decided_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          access_point_id?: string | null;
          invite_id?: string | null;
          resident_id?: string | null;
          visitor_id?: string | null;
          plate?: string | null;
          direction?: string;
          decision?: string;
          reason?: string | null;
          decided_by?: string | null;
          decided_at?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      gate_commands: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          access_point_id: string;
          access_event_id: string | null;
          command: string;
          provider: string;
          status: string;
          requested_by: string | null;
          requested_at: string;
          executed_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          access_point_id: string;
          access_event_id?: string | null;
          command: string;
          provider?: string;
          status?: string;
          requested_by?: string | null;
          requested_at?: string;
          executed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          access_point_id?: string;
          access_event_id?: string | null;
          command?: string;
          provider?: string;
          status?: string;
          requested_by?: string | null;
          requested_at?: string;
          executed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      gatehouse_occurrences: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          title: string;
          description: string | null;
          severity: string;
          status: string;
          created_by: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          title: string;
          description?: string | null;
          severity?: string;
          status?: string;
          created_by?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          title?: string;
          description?: string | null;
          severity?: string;
          status?: string;
          created_by?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          tenant_id: string | null;
          condominium_id: string | null;
          actor_profile_id: string | null;
          actor_user_id: string | null;
          action: string;
          entity_table: string;
          entity_id: string | null;
          event_type: string;
          source: string;
          severity: string;
          occurred_at: string;
          correlation_id: string | null;
          retention_policy: string;
          retention_until: string | null;
          redaction_status: string;
          before_state: Json | null;
          after_state: Json | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          condominium_id?: string | null;
          actor_profile_id?: string | null;
          actor_user_id?: string | null;
          action: string;
          entity_table: string;
          entity_id?: string | null;
          event_type?: string;
          source?: string;
          severity?: string;
          occurred_at?: string;
          correlation_id?: string | null;
          retention_policy?: string;
          retention_until?: string | null;
          redaction_status?: string;
          before_state?: Json | null;
          after_state?: Json | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: never;
        Relationships: [];
      };
      audit_retention_policies: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string | null;
          event_type: string;
          retention_days: number;
          legal_basis: string;
          status: string;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id?: string | null;
          event_type: string;
          retention_days: number;
          legal_basis?: string;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string | null;
          event_type?: string;
          retention_days?: number;
          legal_basis?: string;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log_export_requests: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string | null;
          requested_by: string | null;
          status: string;
          format: string;
          filters: Json;
          file_path: string | null;
          exported_at: string | null;
          expires_at: string | null;
          failure_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id?: string | null;
          requested_by?: string | null;
          status?: string;
          format?: string;
          filters?: Json;
          file_path?: string | null;
          exported_at?: string | null;
          expires_at?: string | null;
          failure_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string | null;
          requested_by?: string | null;
          status?: string;
          format?: string;
          filters?: Json;
          file_path?: string | null;
          exported_at?: string | null;
          expires_at?: string | null;
          failure_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vehicle_plate_blacklist: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          plate: string;
          reason: string | null;
          status: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          plate: string;
          reason?: string | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          plate?: string;
          reason?: string | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      visitor_vehicle_accesses: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          invite_id: string | null;
          unit_id: string | null;
          plate: string;
          visitor_name: string;
          status: string;
          entered_at: string;
          exited_at: string | null;
          entry_validated_by: string | null;
          exit_validated_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          invite_id?: string | null;
          unit_id?: string | null;
          plate: string;
          visitor_name: string;
          status?: string;
          entered_at?: string;
          exited_at?: string | null;
          entry_validated_by?: string | null;
          exit_validated_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          invite_id?: string | null;
          unit_id?: string | null;
          plate?: string;
          visitor_name?: string;
          status?: string;
          entered_at?: string;
          exited_at?: string | null;
          entry_validated_by?: string | null;
          exit_validated_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      resident_favorite_visitors: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id: string | null;
          visitor_name: string;
          visitor_phone: string | null;
          plate: string | null;
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id?: string | null;
          visitor_name: string;
          visitor_phone?: string | null;
          plate?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          resident_id?: string;
          unit_id?: string | null;
          visitor_name?: string;
          visitor_phone?: string | null;
          plate?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      resident_access_approvals: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id: string | null;
          visitor_name: string;
          visitor_phone: string | null;
          plate: string | null;
          status: string;
          requested_by: string | null;
          decided_by: string | null;
          decided_at: string | null;
          expires_at: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          resident_id: string;
          unit_id?: string | null;
          visitor_name: string;
          visitor_phone?: string | null;
          plate?: string | null;
          status?: string;
          requested_by?: string | null;
          decided_by?: string | null;
          decided_at?: string | null;
          expires_at?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          resident_id?: string;
          unit_id?: string | null;
          visitor_name?: string;
          visitor_phone?: string | null;
          plate?: string | null;
          status?: string;
          requested_by?: string | null;
          decided_by?: string | null;
          decided_at?: string | null;
          expires_at?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      operational_ai_analyses: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          provider: string;
          model: string | null;
          event_source: string;
          event_id: string | null;
          category: string;
          risk_level: string;
          risk_score: number;
          confidence: number;
          summary: string;
          recommendations: Json;
          signals: Json;
          status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          provider?: string;
          model?: string | null;
          event_source: string;
          event_id?: string | null;
          category: string;
          risk_level: string;
          risk_score: number;
          confidence: number;
          summary: string;
          recommendations?: Json;
          signals?: Json;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          provider?: string;
          model?: string | null;
          event_source?: string;
          event_id?: string | null;
          category?: string;
          risk_level?: string;
          risk_score?: number;
          confidence?: number;
          summary?: string;
          recommendations?: Json;
          signals?: Json;
          status?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      operational_ai_alerts: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          analysis_id: string | null;
          alert_type: string;
          severity: string;
          title: string;
          description: string | null;
          status: string;
          assigned_to: string | null;
          acknowledged_by: string | null;
          acknowledged_at: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          analysis_id?: string | null;
          alert_type: string;
          severity?: string;
          title: string;
          description?: string | null;
          status?: string;
          assigned_to?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          analysis_id?: string | null;
          alert_type?: string;
          severity?: string;
          title?: string;
          description?: string | null;
          status?: string;
          assigned_to?: string | null;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      doorman_assistant_sessions: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          operator_profile_id: string | null;
          status: string;
          title: string | null;
          last_message_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          operator_profile_id?: string | null;
          status?: string;
          title?: string | null;
          last_message_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          condominium_id?: string;
          operator_profile_id?: string | null;
          status?: string;
          title?: string | null;
          last_message_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      doorman_assistant_messages: {
        Row: {
          id: string;
          tenant_id: string;
          condominium_id: string;
          session_id: string;
          role: string;
          content: string;
          model: string | null;
          safety_flags: Json;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          condominium_id: string;
          session_id: string;
          role: string;
          content: string;
          model?: string | null;
          safety_flags?: Json;
          metadata?: Json;
          created_at?: string;
        };
        Update: never;
        Relationships: [];
      };
    };
    Views: {
      audit_log_export_view: {
        Row: {
          id: string;
          tenant_id: string | null;
          condominium_id: string | null;
          actor_profile_id: string | null;
          actor_user_id: string | null;
          event_type: string;
          action: string;
          entity_table: string;
          entity_id: string | null;
          source: string;
          severity: string;
          occurred_at: string;
          correlation_id: string | null;
          retention_policy: string;
          retention_until: string | null;
          redaction_status: string;
          metadata: Json;
          created_at: string;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
